### ISSUE TITLE
Host not found (non-authoritative), try again later

### ISSUE THREAD

**Issue by TheLowHigh** [qBitMF/qBitMF#3]
After following every step of the documentation, when trying to download a torrent, the following message can be found on the trackers tab :
`Host not found (non-authoritative), try again later`
I'm using mullvad as a vpn.
![image](https://user-images.githubusercontent.com/71192394/187043127-13cf5de2-380f-4665-998b-3285ba362228.png)

Please let me know if I need to provide any additional informations.
Thank you.

**Comment by TheLowHigh** [comment]
I tried on ubuntu and the issue wasn't there anymore. (I had this problem with debian)

**Comment by Ronniie** [comment]
Running into this error as well, using Ubuntu. Any possible resolutions?

**Comment by k3d3** [comment]
I've been told that the "resilient" route type only exists in newer Linux kernels, which requires removing these two lines https://github.com/qBitMF/qBitMF/blob/master/images/qbitmf/make-wg-netns.py#L86-L87

Can you try removing those lines and rebuilding? If that makes it work then I'll make a PR to remove them.

(Resilient routing's only necessary to keep connections open when new interfaces are added, but since the number of interfaces stay the same for the life of the container, this doesn't matter.)

**Comment by Ronniie** [comment]
Thanks for the quick response, seems like it didn't affect the outcome. I'm also using Mullvad to provide some context.

**Comment by augustabt** [comment]
Also had this same issue, deleting these lines solved the problem
https://github.com/qBitMF/qBitMF/blob/master/images/qbitmf/make-wg-netns.py#L88-L91

For reference I am building and running the container on Ubuntu 20.04.5 LTS. I believe these are the lines that set the resilient route type and therefore shouldn't make a difference. Please correct me if I am wrong @k3d3
